[[crates]]
name = "steering"
source = "crates"

[[crates]]
name = "aspen"
source = "crates"

[[crates]]
name = "piston-ai_behavior"
source = "crates"

[[crates]]
name = "pathfinding"
source = "crates"
